# Generated by Django 4.0.2 on 2022-02-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
