# Generated by Django 4.0.3 on 2022-03-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0002_remove_champion_aevasion_remove_champion_ahealth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='armour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armour', to='TheGame.specificitem'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='auxItem1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aux1', to='TheGame.specificitem'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='auxItem2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aux2', to='TheGame.specificitem'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='auxItem3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aux3', to='TheGame.specificitem'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='primaryWeapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pWeapon', to='TheGame.specificweapon'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='secondaryWeapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sWeapon', to='TheGame.specificweapon'),
        ),
    ]
