# Generated by Django 4.0.3 on 2022-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0003_alter_champion_armour_alter_champion_auxitem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseweapon',
            name='ap_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
