# Generated by Django 4.0.3 on 2022-03-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0004_remove_championitems_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championitems',
            name='itemLevel',
        ),
        migrations.AlterField(
            model_name='championitems',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheGame.champion'),
        ),
        migrations.AlterField(
            model_name='championitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheGame.item'),
        ),
    ]
