# Generated by Django 4.0.3 on 2022-03-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_alter_resource_name'),
        ('TheGame', '0005_remove_championitems_itemlevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='item',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='priceRes1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='priceRes1', to='Resources.resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='priceRes2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priceRes2', to='Resources.resource'),
        ),
        migrations.AddField(
            model_name='item',
            name='priceRes3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priceRes3', to='Resources.resource'),
        ),
    ]
