# Generated by Django 4.0.3 on 2022-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0006_rename_price_item_price1_item_price2_item_price3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='shieldValue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
