# Generated by Django 4.0.1 on 2022-03-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_merge_20220227_1644'),
        ('TheGame', '0007_pstat_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pstat',
            name='username',
        ),
        migrations.AddField(
            model_name='pstat',
            name='player',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='Login.player'),
            preserve_default=False,
        ),
    ]
