# Generated by Django 4.0.3 on 2022-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0007_baseitem_shieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='sprite',
            field=models.CharField(default='hacker', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='sprite',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
