# Generated by Django 4.0.2 on 2022-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0008_remove_pstat_username_pstat_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pstat',
            name='accuracy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pstat',
            name='attackSpeed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pstat',
            name='damage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pstat',
            name='pHealth',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pstat',
            name='pToughness',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
