# Generated by Django 4.0.3 on 2022-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0008_champion_sprite_item_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.CharField(default='shiv', max_length=50),
        ),
    ]
