# Generated by Django 4.0.3 on 2022-03-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_merge_20220227_1644'),
        ('TheGame', '0009_alter_pstat_accuracy_alter_pstat_attackspeed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pHealth', models.PositiveIntegerField(default=100)),
                ('pToughness', models.PositiveIntegerField(default=1)),
                ('pEvasion', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=1)),
                ('accuracy', models.PositiveIntegerField(default=1)),
                ('attackSpeed', models.PositiveIntegerField(default=1)),
                ('aHealth', models.PositiveIntegerField(default=0)),
                ('aToughness', models.PositiveIntegerField(default=0)),
                ('aEvasion', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.player')),
            ],
        ),
        migrations.DeleteModel(
            name='pStat',
        ),
    ]
