# Generated by Django 4.0.2 on 2022-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0011_item_championitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Stat2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='Stat3',
            field=models.IntegerField(default=1),
        ),
    ]
