# Generated by Django 4.0.3 on 2022-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheGame', '0012_item_stat2_item_stat3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('damageNumber', models.IntegerField()),
                ('damageInstances', models.IntegerField()),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Stat1',
            new_name='armourValue',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Stat2',
            new_name='vitalityBoost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Stat3',
        ),
        migrations.AddField(
            model_name='championitems',
            name='glory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='specialAbilities',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
