# Generated by Django 4.0.3 on 2022-03-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('TheGame', '0013_weapon_rename_stat1_item_armourvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('titem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheGame.titem')),
                ('armourValue', models.IntegerField()),
                ('vitalityBoost', models.IntegerField()),
                ('specialAbilities', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('TheGame.titem',),
        ),
        migrations.CreateModel(
            name='BaseWeapon',
            fields=[
                ('titem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheGame.titem')),
                ('damageNumber', models.IntegerField()),
                ('damageInstances', models.IntegerField()),
                ('range', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('TheGame.titem',),
        ),
        migrations.CreateModel(
            name='tChampionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TheGame.champion')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TheGame.titem')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificItem',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheGame.baseitem')),
                ('level', models.IntegerField()),
                ('glory', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('TheGame.baseitem',),
        ),
        migrations.CreateModel(
            name='SpecificWeapon',
            fields=[
                ('baseweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheGame.baseweapon')),
                ('level', models.IntegerField()),
                ('glory', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('TheGame.baseweapon',),
        ),
    ]
