# Generated by Django 4.0.2 on 2022-03-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resources', '0002_playerresource_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('QRID', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='QRResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('QRID', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='QRC.qrc')),
                ('resource', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='Resources.resource')),
            ],
        ),
    ]
