# Generated by Django 4.0.1 on 2022-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrc',
            name='QRID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
