# Generated by Django 4.0.1 on 2022-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRC', '0002_alter_qrc_qrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrc',
            name='image',
            field=models.ImageField(default=0, upload_to='qrImages/'),
            preserve_default=False,
        ),
    ]
