# Generated by Django 4.0.2 on 2022-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRC', '0003_qrc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrc',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
