<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-19 15:23
=======
# Generated by Django 4.0.2 on 2022-03-19 15:20
>>>>>>> 777b32f5f0b2b77c009f37d3910625c1d9899106

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRC', '0003_qrc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrc',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
