# Generated by Django 4.0.1 on 2022-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresource',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
