# Generated by Django 4.0.2 on 2022-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='userID',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
