# Generated by Django 4.0.2 on 2022-02-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_player_password_alter_player_userid'),
        ('Login', '0003_player_role_alter_player_password_and_more'),
    ]

    operations = [
    ]
