# Generated by Django 4.0.3 on 2022-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_merge_20220227_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lastResourceTimestamp',
            field=models.TimeField(null=True),
        ),
    ]
