# Generated by Django 4.0.3 on 2022-03-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_player_lastresourcetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lastResourceTimestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
